-- :fennel:1768887988
local colors = require("colors")
vim.api.nvim_set_hl(0, "DashboardHeader", {fg = colors.blue})
vim.api.nvim_set_hl(0, "DashboardKey", {fg = colors.purple})
vim.api.nvim_set_hl(0, "DashboardIcon", {fg = colors.green})
vim.api.nvim_set_hl(0, "DashboardDesc", {fg = colors.green})
vim.api.nvim_set_hl(0, "DashboardFooter", {fg = colors.yellow})
vim.api.nvim_set_hl(0, "BlinkCmpMenu", {bg = "#FFFFFF", fg = "#383A42"})
vim.api.nvim_set_hl(0, "BlinkCmpMenuSelection", {bg = "#F0F4FC", fg = "NONE", bold = true})
vim.api.nvim_set_hl(0, "BlinkCmpMenuBorder", {fg = "#E5E5E5", bg = "#FFFFFF"})
vim.api.nvim_set_hl(0, "BlinkCmpLabelMatch", {fg = "#4078F2", bold = true})
vim.api.nvim_set_hl(0, "BlinkCmpGhostText", {fg = "#A0A1A7"})
vim.api.nvim_set_hl(0, "BlinkCmpSource", {fg = "#A0A1A7", italic = true})
vim.api.nvim_set_hl(0, "BlinkCmpKindFunction", {fg = "#A626A4", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindMethod", {fg = "#A626A4", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindKeyword", {fg = "#A626A4", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindVariable", {fg = "#E45649", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindField", {fg = "#E45649", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindProperty", {fg = "#E45649", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindClass", {fg = "#C18401", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindStruct", {fg = "#C18401", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindInterface", {fg = "#C18401", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindSnippet", {fg = "#50A14F", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindString", {fg = "#50A14F", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindConstant", {fg = "#0184BC", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindFile", {fg = "#4078F2", bg = "NONE"})
vim.api.nvim_set_hl(0, "BlinkCmpKindFolder", {fg = "#4078F2", bg = "NONE"})
return vim.api.nvim_set_hl(0, "SnacksDim", {fg = "#D0D0D0"})